[package]
name = "binary_search_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
default = []

[[bin]]
name = "binary_search_cli"
path = "src/cli.rs"